In [53]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import Functions as f

1. Start by splitting the data 4:1 as training and validation randomly (for grading purposes please use np.random.seed(1)).

In [54]:
data = pd.read_csv('data/cars-mpg.csv').to_numpy()
# split the x_train, y_train, x_test, y_test with sklearn train test split, first row is the label
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data[:,1:], data[:,0], test_size=0.20)


2. Implement the forward selection algorithm as discussed in Lecture 6 (see lecture notes for
details). In the loop use the training MSE to find the best model in each iteration. The
algorithm should produce p + 1 models M0, ..., Mp, where Mi is the best model using
i features. In terms of output, an alternative could be to let the algorithm produce a
p-dimensional vector where its first entry is the feature in M1, its second entry is the new
feature in M2 etc.

In [55]:
num_of_features = x_train.shape[1]
models = f.feature_selection(x_train, y_train, num_of_features, LinearRegression)
for model in models:
    numpy_model = np.array(model[0])
    print(numpy_model[:5, :])
    print("Model features (index from the training data): ", model[1])

0
1
2
3
4
5
6
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Model features (index from the training data):  []
[[1.000e+00 2.164e+03]
 [1.000e+00 1.773e+03]
 [1.000e+00 3.102e+03]
 [1.000e+00 2.965e+03]
 [1.000e+00 4.615e+03]]
Model features (index from the training data):  [3]
[[1.000e+00 2.164e+03 7.600e+01]
 [1.000e+00 1.773e+03 7.100e+01]
 [1.000e+00 3.102e+03 7.400e+01]
 [1.000e+00 2.965e+03 7.800e+01]
 [1.000e+00 4.615e+03 7.000e+01]]
Model features (index from the training data):  [3, 5]
[[1.000e+00 2.164e+03 7.600e+01 1.000e+00]
 [1.000e+00 1.773e+03 7.100e+01 3.000e+00]
 [1.000e+00 3.102e+03 7.400e+01 1.000e+00]
 [1.000e+00 2.965e+03 7.800e+01 1.000e+00]
 [1.000e+00 4.615e+03 7.000e+01 1.000e+00]]
Model features (index from the training data):  [3, 5, 6]
[[1.000e+00 2.164e+03 7.600e+01 1.000e+00 9.800e+01]
 [1.000e+00 1.773e+03 7.100e+01 3.000e+00 7.100e+01]
 [1.000e+00 3.102e+03 7.400e+01 1.000e+00 1.980e+02]
 [1.000e+00 2.965e+03 7.800e+01 1.000e+00 2.000e+02]
 [1.000e+00 4.615e+03 7.000e+